"""init owe schema

Revision ID: accb5327bbbc
Revises: 
Create Date: 2026-04-07 18:07:07.083353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accb5327bbbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    schema='owe'
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['owe.conversations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='owe'
    )
    op.create_index(op.f('ix_owe_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False, schema='owe')
    op.create_table('lead_profiles',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('business_segment', sa.String(length=32), nullable=True),
    sa.Column('annual_usage_mwh', sa.Float(), nullable=True),
    sa.Column('usage_estimated', sa.Boolean(), nullable=False),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.String(length=32), nullable=False),
    sa.Column('contract_expiry_months', sa.Integer(), nullable=True),
    sa.Column('building_age_years', sa.Integer(), nullable=True),
    sa.Column('has_current_provider', sa.Boolean(), nullable=True),
    sa.Column('notes_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['owe.conversations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    schema='owe'
    )
    op.create_table('qualification_decisions',
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['owe.conversations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    schema='owe'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualification_decisions', schema='owe')
    op.drop_table('lead_profiles', schema='owe')
    op.drop_index(op.f('ix_owe_conversation_messages_conversation_id'), table_name='conversation_messages', schema='owe')
    op.drop_table('conversation_messages', schema='owe')
    op.drop_table('conversations', schema='owe')
    # ### end Alembic commands ###
